changes for python 3
adsabs/ADSCitationCapture pull request #37
Opened 2021-07-11 15:49 UTC by spacemansteve

not yet ready to merge, unit test pass but warnings have not been reviewed/fixed

2021-07-14 13:00 UTC, marblestation requested changes
This is good progress, there are just some suggestions and questions to be addressed before moving forward.

2021-07-14 13:00 UTC, marblestation commented on ADSCitationCapture/db.py
> +        if type(raw_metadata) is not str:
This transformation is good, but I was just wondering if we could improve the original code by being more explicit and having:

```python
if type(raw_metadata) is bytes:
```

2021-07-14 13:00 UTC, marblestation commented on ADSCitationCapture/delta_computation.py
> +        if n_all_fields_null and n_all_fields_null > 0:
In what situation can `n_all_fields_null` be `None` so that we need to add this condition here? And also, if there is a situation where we get `None`, is it correct to continue without raising an exception?

2021-07-14 13:00 UTC, marblestation commented on ADSCitationCapture/delta_computation.py
> +        if n_too_many_fields_not_null and n_too_many_fields_not_null > 0:
In what situation can `n_too_many_fields_not_null` be `None` so that we need to add this condition here? And also, if there is a situation where we get `None`, is it correct to continue without raising an exception?

2021-07-14 13:00 UTC, marblestation commented on ADSCitationCapture/delta_computation.py
> +        if n_duplicates and  n_duplicates > 0:
In what situation can `n_duplicates` be `None` so that we need to add this condition here? And also, if there is a situation where we get `None`, is it correct to continue without raising an exception?

2021-07-14 13:00 UTC, marblestation commented on ADSCitationCapture/doi.py
> +        content = r.content.decode('UTF-8')
After a bit of reading, it looks like we could (and probably should) use `r.text` instead since that one would take into account the encoding provided by the server response (see [docs](https://docs.python-requests.org/en/master/user/quickstart/#response-content)).

2021-07-14 13:00 UTC, marblestation commented on ADSCitationCapture/forward.py
> +    author_facet_hier = list(itertools.chain.from_iterable(list(zip(["0/"+a for a in normalized_authors], ["1/"+a[0]+"/"+a[1] for a in zip(normalized_authors, authors)]))))
We do not need the new `list(..)` (the one between `from_iterable` and `zip`).

2021-07-14 13:00 UTC, marblestation commented on ADSCitationCapture/tests/test_base.py
> +        for table_name in list(Base.metadata.tables.keys()):
We do not need `list` here.

2021-07-14 13:00 UTC, marblestation commented on ADSCitationCapture/tests/test_run.py
>                              pudb.set_trace()
This is unrelated to the Python 3 conversion, but it looks like we have a try/except here that would trigger a debugger. Most probably this is something I committed by mistake and we could remove it.

2021-07-14 13:00 UTC, marblestation commented on run.py
> +            print(("Calling 'task_process_citation_changes' with '{}'".format(str(changes))))
We added unnecessary extra parenthesis here.

2021-07-14 13:00 UTC, marblestation commented on run.py
> +    print(("Preparing diagnostics temporary file '{}'...".format(tmp_file.name)))
We added unnecessary extra parenthesis here.

2021-07-14 13:00 UTC, marblestation commented on run.py
> +        print(("\t{}".format(tmp_str)))
We added unnecessary extra parenthesis here.

2021-07-14 14:54 UTC, spacemansteve commented on ADSCitationCapture/delta_computation.py
> +        if n_duplicates and  n_duplicates > 0:
Without this change 14 unit tests fail because n_duplicates is null.  I think the sqlalchemy's count function can return None if the sql select returned NULL.

2021-07-14 14:56 UTC, spacemansteve commented on ADSCitationCapture/delta_computation.py
> +        if n_too_many_fields_not_null and n_too_many_fields_not_null > 0:
All test pass without this change.  It was added to parallel the change to the if statement for n_duplicates.

2021-07-14 14:56 UTC, spacemansteve commented on ADSCitationCapture/delta_computation.py
> +        if n_all_fields_null and n_all_fields_null > 0:
All test pass without this change.  It was added to parallel the change to the if statement for n_duplicates.

2021-07-15 12:22 UTC, marblestation commented on ADSCitationCapture/delta_computation.py
> +        if n_duplicates and  n_duplicates > 0:
Thanks for the clarification, this made me review the SQL statements once more and you are right that for the duplicate verification we are filtering with a `HAVING` statement:

https://github.com/adsabs/ADSCitationCapture/blob/ba912e4225724d506942bc94a909eff42110948e/ADSCitationCapture/delta_computation.py#L358-L362

Therefore, it makes sense that a `None` value is returned if there are no duplicates. If there were duplicates, the SQL statement is going to return a list of counts (as many as detected duplicate entries). We are then calling `scalar()` which, according to the [docs](https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.scalar):

```
Return the first element of the first result or None if no rows present. If multiple rows are returned, raises MultipleResultsFound.
```

Therefore, if the SQL finds more than one duplicate, calling `scalar` is going to throw an exception. I think we should change the SQL to something like:

```python
count_duplicates_sql = \
    "select count(*) \
        from (select count(*) \
                    from {0}.{1} \
                    group by citing, content \
                    having count(*) > 1) as dups;"
```

This will really return the number of duplicates and if there are none, we will get back a zero. After all, the problem was not with the `if` statement but with the SQL query and I believe we won't need to check if `n_duplicates` is null. Can you check this?

2021-07-15 12:24 UTC, marblestation commented on ADSCitationCapture/delta_computation.py
> +        if n_all_fields_null and n_all_fields_null > 0:
See comment below about `n_duplicates`, its SQL query was different because it had a `HAVING` statement. This SQL query to get `n_all_fields_null` should always return a number.

2021-07-15 12:24 UTC, marblestation commented on ADSCitationCapture/delta_computation.py
> +        if n_too_many_fields_not_null and n_too_many_fields_not_null > 0:
See comment below about `n_duplicates`, its SQL query was different because it had a `HAVING` statement. This SQL query to get `n_too_many_fields_not_null` should always return a number.

2021-07-15 14:27 UTC, spacemansteve commented on ADSCitationCapture/doi.py
> +        content = r.content.decode('UTF-8')
that makes sense

2021-07-15 14:28 UTC, spacemansteve commented on ADSCitationCapture/forward.py
> +    author_facet_hier = list(itertools.chain.from_iterable(list(zip(["0/"+a for a in normalized_authors], ["1/"+a[0]+"/"+a[1] for a in zip(normalized_authors, authors)]))))
removed

2021-07-16 06:57 UTC, marblestation approved these changes
It looks great! Thanks for doing this!

2021-07-16 06:58 UTC, merged