Webhook URL Handling
adsabs/ADSCitationCapture pull request #40
Opened 2021-11-23 13:30 UTC by tjacovich

Modifications to tasks, alembic, database, and webhook to allow for emitting URLs to the broker without adding them to ADS database.

2021-11-24 16:33 UTC, tjacovich commented
Still need to update pytest with  to work with modified webhook and tasks.

2021-12-02 15:43 UTC, tjacovich commented
Finished updating unit tests. Doing final checks before opening PR for review.

2021-12-06 21:18 UTC, tjacovich commented
is_link_alive check for calling get_github_metadata() should be sufficient because malformed urls will bypass the metadata call and only alive links will be processed beyond this point due to checks in other tasks.

2021-12-13 11:06 UTC, marblestation requested changes
This looks very good! I am only asking for the creation of a separate `is_github(url)` function in the `url` module, and a change on the default license to be None when we actually do not know what is the license.

2021-12-13 11:06 UTC, marblestation commented on ADSCitationCapture/api.py
> +    if "github" in domain:
Even if we end up calling `is_github` outside this function, it can be good to also do it here to make sure it is a github url (e.g., if a future developer calls this on a URL without checking previously if it is a github url).

2021-12-13 17:12 UTC, tjacovich commented on ADSCitationCapture/api.py
> +        raise Exception(msg)
Added dedicated `is_github` function in `url` and removed this entire block of code from `get_github_metadata`.

2021-12-13 17:16 UTC, tjacovich commented on ADSCitationCapture/api.py
> +        return {'license_name': license_name, 'license_url': license_url}
That is fair. I had originally written it this way so that it reverts to the default output of the current master branch.  I've now updated `get_github_metadata` so that it is consistent with `tasks.py`. I also removed all the unnecessary `return` calls in `get_github_metadata`.

2021-12-13 17:19 UTC, tjacovich commented on ADSCitationCapture/api.py
> +    if "github" in domain:
Updated check to call `is_github` which includes a stricter check of 
```
if domain.endswith("github.com") return True
```
instead of just looking for "github" in the parsed domain.

2021-12-13 17:23 UTC, tjacovich commented on ADSCitationCapture/tasks.py
> +            license_info = {'license_name': None, 'license_url': None}
changed `is_link_alive` to `is_github`. I used `urllib.parse` for `is_github` instead of a regex because `urllib` is already loaded in another module so it doesn't add any additional dependencies to CitationCapture and the url structure for a github repo is relatively simple.

2022-01-07 08:45 UTC, marblestation approved these changes
This looks good! For the future, I would make the `is_github` and `is_alive` independent, meaning `is_github` only check if it is a github URL but not if it is alive.

2022-01-07 08:49 UTC, merged