Manual Curation of Metadata for Software Records
adsabs/ADSCitationCapture pull request #45
Opened 2022-01-24 16:43 UTC by tjacovich

Added functionality to modify metadata for software records generated by Citation Capture using json input either as input file or as a command line argument.

2022-02-15 19:38 UTC, tjacovich commented
Ended up leaving maintenance_show_metadata in tasks.py because the database functions defined in db.py are built around having access to app as defined in tasks.py. Moving it out of tasks would require rewriting all the db.py functions so they could be called with a generic session passed as an argument instead of app.

2022-02-15 20:36 UTC, tjacovich commented
Finished removing any calls to datacite from manual curation. Rewrote the reset function so that it calls maintenance_metadata, instead of collecting original info from datacite. This means reset can't be used to delete single entries, but I think it makes resets more predictable because everything except for any alternate bibcodes that were originally assigned by CitationCapture are reset to the current datacite metadata.

2022-02-16 17:02 UTC, tjacovich commented
Individual fields can still be edited on the fly without a reset, but the only way to reset one field to the default from datacite is to reset the entire citation target.

2022-02-25 16:37 UTC, marblestation requested changes
Maybe I am misinterpreting this PR, but I have the impression there is a more convenient way to implement this manually curated data.

Right now, when a user specifies some manual curated data for bibcode X, values in `parsed_metadata` get replaced by values from `curated_metadata` and both are stored in the database. So `parsed_metadata`is not really "parsed metadata" anymore but parsed + manual updates.

If a user decides to reset the curated data for bibcode X, it will re-fetch the metadata (which we do not want) and following the logic I am not even sure that the `curated_metadata` field gets reset to an empty value.

Here is what I propose:

- `curated_metadata` field always contains whatever the curator injected or it will be empty if nothing was injected or it was reset
- `parsed_metadata` field always contain the result of parsing the raw metadata
- `parsed_metadata` and `curated_metadata` are only combined on memory (never stored) when a protobuf needs to be send to master, an event needs to be reported to the broker (or probably not for this, I believe we do not send any metadata) or the user requests to show what is in the database

Maybe you have already considered this approach and I am missing some other problem, let's talk about this in our next meeting.

2022-02-25 16:37 UTC, marblestation commented on ADSCitationCapture/tasks.py
> +                        curated_entry[key] = registered_record['curated_metadata'][key]
The task `task_maintenance_curation(dois, bibcodes, curated_entries, reset = False)` can be called with a `curated_entries` that contains an ID (DOI and/or bibcode) and other curated fields. But in this piece of code, we are replacing that information with whatever was previously stored in the database. So if I manually modify the author list on day 1, and on day 2 I manually modify the author list again, it won't happen because the changes from day 1 will override the requested changes on day 2. So I believe we have a flaw in this logic or I am misunderstanding something.

2022-02-25 16:37 UTC, marblestation commented on ADSCitationCapture/tasks.py
> +                updated = db.update_citation_target_metadata(app, registered_record['content'], raw_metadata, parsed_metadata, curated_entry)
This may end up in a potential future bug, the function signature is:

```update_citation_target_metadata(app, content, raw_metadata, parsed_metadata, curated_metadata = {}, status=None):```

`curated_metadata` is a named argument but in our call here we do not name it, so it is based on its position, which can change in the future and will break things. Add the name of the argument to make sure it is always properly assigned to the right argument.

```
updated = db.update_citation_target_metadata(app, registered_record['content'], raw_metadata, parsed_metadata, curated_metadata=curated_entry)
```

2022-02-25 16:57 UTC, tjacovich commented on ADSCitationCapture/tasks.py
> +                        curated_entry[key] = registered_record['curated_metadata'][key]
My understanding of this section is that it will pull from the old curated metadata only if the key is not specified in the new metadata. That way the curators only have to provide the fields they currently want to update and anything that wasn't explicitly updated will just be filled in by any previous curated metadata.

2022-02-25 17:19 UTC, tjacovich commented on ADSCitationCapture/tasks.py
> +                task_maintenance_metadata.delay([registered_record['content']],[registered_record['bibcode']],reset = True)
This is true. The fetch was necessary because manual curation does not currently preserve the original parsed metadata. The reason for that was to make sure `parsed_metadata` in CitationCapture matched that being sent. It also simplified any resends that might need to occur because every citation would be treated identically and we wouldn't have to rebuild the metadata on the fly.

2022-02-25 17:35 UTC, tjacovich commented on run.py
> +                maintenance_curation(args.input_filename, dois, bibcodes, json, args.reset, args.show)
Updated. I had originally pulled from the formatting for diagnose, but you are 100% correct that import json and the json arg should interfere. Oddly enough it did function for my test cases, but I couldn't tell you why it did.

2022-02-25 17:48 UTC, tjacovich commented on run.py
> +                        help='Delete manually curated metadata for supplied bibcodes.')
Updated text. Need to finish modifying resets to reflect this.

2022-02-25 17:49 UTC, tjacovich commented on run.py
> +            print(curated_entries)
Yes. That is my mistake.

2022-02-25 17:55 UTC, tjacovich commented on run.py
> +                        help='Path to the input file (e.g., refids.dat) file that contains the citation list')
It is. I overlooked the distinction between citation list and the curated metadata files for this operation, and didn't catch it on review.

2022-02-25 17:57 UTC, tjacovich commented on run.py
> +                curated_entries = [json.loads(json)]
Somehow the interpreter worked out calls to the package vs. calls to the passed argument so tests functioned properly, but realistically this shouldn't work.

2022-02-25 17:57 UTC, tjacovich commented on run.py
> +                    curated_entries[0]['bibcode'] = bibcodes[0]
Added error if more than one is specified with accompanying message.

2022-02-25 17:58 UTC, tjacovich commented on run.py
> +                        help='Manually edit Citation Capture generated citation metadata for specific entries.')
Updated text.

2022-02-25 18:03 UTC, tjacovich commented on run.py
> +                maintenance_curation(args.input_filename, dois, bibcodes, json, args.reset, args.show)
I also put a warning on any calls that specify `--input_filename` with command line lists of dois, bibcodes, or json informing the user that only the file will be used.

2022-02-25 18:12 UTC, tjacovich commented on run.py
> +            bibcodes = list(filter(lambda entry:(entry.get('bibcode', None) is not None and entry.get('doi', None) is None), curated_entries))
Lists have been updated.

2022-02-25 19:07 UTC, tjacovich commented
Sounds good. I’ve already made the changes related to errors and exception handling. My main rationale for handling parsed metadata they way I did was that it condensed the locations where it mattered whether curated metadata existed to just the two maintenance functions as any other function would only have to worry about the parsed metadata. My main concern with doing it on the fly is that it would mean things like new citations to existing targets would have to get the metadata and then deal with modifying it before being able to send it.

2022-03-01 18:43 UTC, tjacovich commented
Need to do more testing of alembic upgrade on a database generated by HEAD on master branch.

2022-03-04 20:16 UTC, tjacovich commented
Finished modifying alembic revision so that the bibcodes column is populated on upgrade. Needed separate db functions because alembic initiates its own db session that lasts for the entire upgrade, so any calls using app hang indefinitely. This is fixed by adding modified functions that take the session as a direct argument. Additional functions containing the session commands were added to reduce the amount of repeated code in db.py

2022-03-04 21:39 UTC, tjacovich commented
Issue with manually added alternate bibcodes: If there are no alternate bibcodes in the parsed_metadata, parsed_metadata does not have the attribute alternate_bibcode and the generate_modified_metadata fails to set the value and clears alternate_bibcodes from curated_metadata.

2022-03-21 16:17 UTC, marblestation approved these changes
Thanks!!

2022-03-21 16:17 UTC, marblestation commented on ADSCitationCapture/tasks.py
> +                    curated_metadata['alternate_bibcode'] = list(set(alternate_bibcode))
Optimize

2022-03-21 16:17 UTC, marblestation commented on ADSCitationCapture/tasks.py
>              #regenerate bibcode with curated_metadata and append old bibcode to alternate_bibcode
Indentation problem?

2022-03-21 16:17 UTC, marblestation commented on ADSCitationCapture/tasks.py
>              #Repopulate parsed_metadata with expected bibcode information from DataCite
Update & move within the `else` block

2022-03-22 13:12 UTC, merged